baseURL = "https://litefx.crudolph.io/"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
theme = "hugo-scroll"
title = "LiteFX - Open-source, modern and flexible computer graphics and rendering engine, written in C++20 with support for Vulkan ğŸŒ‹ and DirectX 12 â."
publishDir = "../"

[params]
    copyright = "Â© 2021 Carsten Rudolph"
    description = "Open-source, modern and flexible computer graphics and rendering engine, written in C++20 with support for Vulkan ğŸŒ‹ and DirectX 12 â."
    favicon = "favicon.ico"
    images = ["img/banner_m.jpg"]
    title = "LiteFX - Open-source, modern and flexible computer graphics and rendering engine, written in C++20 with support for Vulkan ğŸŒ‹ and DirectX 12 â."
    # hidedesignbyline = true

    [params.meta]
        keywords = "LiteFX, Vulkan, DirectX 12, C++20, Engine, Rendering, Real-Time, Computer Graphics, Open Source, C++, Software, 3D, Game Engine, Git, GitHub"
